namespace:
  name: prod
service:
  port: 7111
image:
  repository: "nikhilsuper/techtrends:"
  tag: 2
  pullPolicy: Always
replicaCount: 5
resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
containerPort: 3111