namespace:
  name: prod
service:
  port: 7111
image:
  repository: "nikhilsuper/techtrends:"
  tag: 2
  pullPolicy: Always
replicaCount: 5
resources:
  requests: 
    memory: 90Mi
    cpu: 200m
  limits: 
    memory: 128Mi
    cpu: 300m
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
containerPort: 3111