namespace: 
  name: staging
service: 
  port: 5111
replicaCount: 3
resources: 
  requests: 
    memory: 90Mi
    cpu: 100m
  limits: 
    memory: 128Mi
    cpu: 250m
image:
  repository: "nikhilsuper/techtrends:"
  tag: 2
  pullPolicy: Always
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
containerPort: 3111